spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/webshop
    username: ${POSTGRES_USER:shop}
    password: ${POSTGRES_PASSWORD:shop}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    show-sql: false

  lifecycle:
    timeout-per-shutdown-phase: 20s

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

  thymeleaf:
    cache: true

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never  # lieber nur im DEV-Profil volle Stacktraces anzeigen

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level [%logger{36}] - %msg%n"
  level:
    org.springframework.web: INFO
    org.thymeleaf: INFO
    com.example.shop: DEBUG  # eigene Logs für dein Projekt
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
