spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/webshop
    username: shop
    password: shop
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
  thymeleaf:
    cache: false

server:
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG
